---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

env:
  global:
    - JOBS=1
  matrix:
    - APP=examples/auth
    - APP=examples/component-composition
    - APP=examples/components
    - APP=examples/core-concepts
    - APP=examples/dependencies
    - APP=examples/ember-data
    - APP=examples/example-addon
    - APP=examples/object-model
    - APP=examples/routing
    - APP=examples/services
    - APP=examples/templates
    - APP=examples/web-sockets
    - APP=bootstrap
    - APP=tomster-player

install:
  - yarn install --pure-lockfile

script:
  - cd $APP
  - yarn run lint:hbs
  - yarn run lint:js
  - yarn test

notifications:
  email: false
